name: Build sitemap

on:
  push:
    branches: [main] # or 'master' if that’s your default
  workflow_dispatch: # lets you run it manually from the Actions tab

permissions:
  contents: write # allow commit & push
jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps (none for now)
        run: echo "No external packages needed"

      - name: Build sitemap.xml
        run: |
          python scripts/generate_sitemap.py

      - name: Commit & push if sitemap changed
        run: |
          if git diff --quiet sitemap.xml; then
            echo "No changes to sitemap."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add sitemap.xml
            git commit -m "chore: update sitemap [skip ci]"
            git push
          fi
